mod initialize_empty_cells;
pub mod initialize_grid;
pub mod model;
pub mod solver;
pub mod solver_helper;
pub(crate) mod utilities;
pub mod validator;
pub mod naked_tuplets_stategies;
pub mod hidden_tuplets_strategies;
mod x_wing_strategy;
mod simple_coloring;
